def test_error(test_file, prediction_file):
	